// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAv4vVjcw5kSMcbJuYyfjTUKa-OCaf4Uw',
    appId: '1:853036839543:web:dae300b3c797601daf4c72',
    messagingSenderId: '853036839543',
    projectId: 'harish-spotify-demo',
    authDomain: 'harish-spotify-demo.firebaseapp.com',
    storageBucket: 'harish-spotify-demo.appspot.com',
    measurementId: 'G-XPEGH2NGFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjbnM6gDel-dYS3gdUml2x5bL13wYipNY',
    appId: '1:853036839543:android:25a44cfd39e33893af4c72',
    messagingSenderId: '853036839543',
    projectId: 'harish-spotify-demo',
    storageBucket: 'harish-spotify-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZpv2eU3PpvwNWk0izYmxXs6UcwHbqjeA',
    appId: '1:853036839543:ios:8940aca512eda5acaf4c72',
    messagingSenderId: '853036839543',
    projectId: 'harish-spotify-demo',
    storageBucket: 'harish-spotify-demo.appspot.com',
    iosBundleId: 'com.example.spotifyTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZpv2eU3PpvwNWk0izYmxXs6UcwHbqjeA',
    appId: '1:853036839543:ios:8940aca512eda5acaf4c72',
    messagingSenderId: '853036839543',
    projectId: 'harish-spotify-demo',
    storageBucket: 'harish-spotify-demo.appspot.com',
    iosBundleId: 'com.example.spotifyTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAv4vVjcw5kSMcbJuYyfjTUKa-OCaf4Uw',
    appId: '1:853036839543:web:df0a0cec8be39243af4c72',
    messagingSenderId: '853036839543',
    projectId: 'harish-spotify-demo',
    authDomain: 'harish-spotify-demo.firebaseapp.com',
    storageBucket: 'harish-spotify-demo.appspot.com',
    measurementId: 'G-SEM328P50T',
  );
}
